### ISSUE TITLE
What's the performance difference if joint train directly without pretrain against pretrain firstly?

### ISSUE THREAD

**Issue by SkyAndCloud** [pluiez/ABD-NMT#1]
Hi, you wrote that pretrain is preferred, but not required in this model and you didn't mention pretrain in your paper. I'm reproducing your results on nist zh-en dataset **without pretrain**. Now it's epoch 3 and valid bleu which is reported by your code is **only 3.82**. Hence, what's the difference whether or not to pretrain or there is something wrong in my config?
My running config:
```
python -u rnnsearch.py train \
    --corpus corpus/train.src corpus/train.trg \
    --vocab corpus/zh.vocab.pkl corpus/en.vocab.pkl \
    --method concat \
    --softk 1 \
    --lambda 0.5 \
    --ext-val-script scripts/validate-zhen.sh \
    --model zhen \
    --embdim 620 620 \
    --hidden 1000 1000 1000 \
    --maxhid 500 \
    --deephid 620 \
    --maxpart 2 \
    --alpha 5e-4 \
    --norm 1.0 \
    --batch 80 \
    --maxepoch 20 \
    --seed 1235 \
    --freq 500 \
    --vfreq 1500 \
    --sfreq 500 \
    --sort 32 \
    --validation corpus/devset1_2.lc.zh \
    --references corpus/devset1_2.lc.en0  corpus/devset1_2.lc.en1 corpus/devset1_2.lc.en2 corpus/devset1_2.lc.en3 \
    --optimizer rmsprop \
    --shuffle 1 \
    --keep-prob 0.7 \
    --limit 50 50 \
    --delay-val 1 \
    --no-overwrite 1 \
    2>&1 | tee train1.log
```

Here is the translation sample, also bad.
![image](https://user-images.githubusercontent.com/12583017/46707887-779c4900-cc6e-11e8-84a6-f428f9ac746e.png)

Here is the bleu in third epoch 3000th batch.
![image](https://user-images.githubusercontent.com/12583017/46707894-83880b00-cc6e-11e8-881a-85e5ca856c9b.png)

**Comment by alphadl** [comment]
have you solved your problems? I even think that the improvement of this paper comes from the pretrain-ed r2l parameters...
