### ISSUE TITLE
Missing path folder

### ISSUE THREAD

**Issue by sanjita-suresh** [pluiez/ABD-NMT#2]
I was trying this tutorial to build a NMT from chinese-english but I am getting error in building vocabulary as --corpus /path/to/train.cn is missing.

**Comment by pluiez** [comment]
Hi, sorry for getting back to you so late.

What do you mean by saying "missing"? That script is rather simple, you can check it yourself for error inspection.

**Comment by sanjita-suresh** [comment]
Hi @pluiez, I found that the training data was missing and I couldn't get it for free.

**Comment by pluiez** [comment]
Hi, you can use WMT data as an alternative since the Chinese English dataset comes from LDC and thus it's not freely available.

**Comment by sanjita-suresh** [comment]
Thanks a lot for your reply. May be I will give it a try later.
